### ISSUE TITLE
"Any key down" events

### ISSUE THREAD

**Issue by JaviCepa** [screenshakes/Desktopia#1]
Is there an easy way to listen to "any key down" events?

Btw, thanks for this amazing piece of code. I'm loving it! :D

**Comment by screenshakes** [comment]
Hey, there this 3 any key functions in Desktopia.Inputs : GetAnyKey, GetAnyKeyDown, GetAnyKeyUp
Alternatively you can also add a key down event with AddOnKeyDown

**Comment by JaviCepa** [comment]
My bad! >_<
Thanks for pointing out!
