### ISSUE TITLE
If running in editor, always disable window mode features ("always on top"/"transparent"/"clickthrough")

### ISSUE THREAD

**Issue by JaviCepa** [screenshakes/Desktopia#2]
I sometimes accidentally click play in editor scenes, the windows gets all messed up and I have to restart Unity.
It'd be nice to have an option to disable the window options while in editor mode (always on top/transparent/clickthrough).

I can't think of any cases where it should be interesting to have them enabled on editor.

A warning could be displayed instead.

**Comment by screenshakes** [comment]
Thank you, I added this in https://github.com/screenshakes/Desktopia/commit/bd6f2e5cfbf7fa6849c456ff679331d3de9a7eba.
